name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev
    
    - uses: actions/checkout@v3

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    
    - name: make
      run: cd build && make
    
    - name: Run Test
      run: /home/runner/work/cpp_project_ci_cd/cpp_project_ci_cd/build/test/cpp_project_ci_cd.test
      
