name: cpp_project_ci_cd-Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest manually
      run:
        echo "Hi"
        ls -lrth
        sudo apt-get install libgtest-dev
        cd /usr/src/googletest/googletest
        sudo mkdir build
        cd build
        sudo cmake ..
        sudo make
        sudo cp libgtest* /usr/lib/
        #cd ..
        #sudo rm -rf build
        sudo mkdir /usr/local/lib/googletest
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/googletest/libgtest.a
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/googletest/libgtest_main.a
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: make
      run: cd build && make
    - name: Run Test
      run: /home/runner/work/cpp_project_ci_cd/cpp_project_ci_cd/build/test/cpp_project_ci_cd.test

